---
inherit: base.yml
applications:
- name: crime-data-explorer-noe
  host: crime-data-explorer-noe
  buildpack: nodejs_buildpack
  memory: 256M
  domain: fr.cloud.gov
  instances: 2
env:
  CDE_API: 'http://api.usa.gov/crime/fbi/ucr/sapi'
  NEW_RELIC_ENABLED: false
services:
  - crime-data-api-key-development
